package com.heiha.example.springboot.psql.po;

public class TTest extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbg.generated
     */
    public TTest(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    public TTest() {}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.id
     *
     * @return the value of t_test.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.name
     *
     * @return the value of t_test.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }
}